name: LME
channels:
  - conda-forge
dependencies:
  - python=3.9
  - cudatoolkit-dev=11.3.1
  - cudatoolkit=11.3
  - pip
  - pip:
    - torch --extra-index-url https://download.pytorch.org/whl/cu113
    - transformers==4.26.1
    - accelerate==0.16.0
    - sentencepiece==0.1.97
    - deepspeed==0.8.1
    - mpi4py==3.1.4
    - sacrebleu==2.3.1
    - datasets==2.9.0
    - evaluate==0.4.0
    - tensorboard==2.12.0
    - -e .
