name: LME
channels:
  - conda-forge
dependencies:
  - python=3.10
  - cudatoolkit-dev=11.7.0
  - cudatoolkit=11.8.0
  - pip
  - pip:
    - torch --extra-index-url https://download.pytorch.org/whl/cu117
    - transformers==4.27.1
    - accelerate==0.17.1
    - sentencepiece==0.1.97
    - deepspeed==0.8.2
    - mpi4py==3.1.4
    - sacrebleu==2.3.1
    - datasets==2.10.1
    - evaluate==0.4.0
    - tensorboard==2.12.0
    - -e .
