name: LME
channels:
  - conda-forge
dependencies:
  - python=3.9
  - cudatoolkit-dev=11.3.1
  - cudatoolkit=11.3
  - pip
  - pip:
    - torch --extra-index-url https://download.pytorch.org/whl/cu113
    - -r file:attention_driven/requirements.txt
