name: LME
channels:
  - conda-forge
dependencies:
  - python=3.9
  - cudatoolkit-dev=11.3.1
  - cudatoolkit=11.3
  - pip
  - pip:
    - torch --extra-index-url https://download.pytorch.org/whl/cu113
    - -r file:requirements_colab.txt
    - accelerate==0.12.0
    - deepspeed==0.7.3
    - pandas==1.5.0
    - git+https://github.com/bri25yu/transformers@fp16-t5-fix
    - -e .
